version: "3.7"

services:
  yelp-test-api:
    container_name: yelp_api_container
    build:
        context: ./
        dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=develop
    volumes:
      - .env:/usr/src/.env